export const SET_LISTINGS = "SET_LISTINGS";
export const CREATE_LISTING = "CREATE_LISTING";
export const UPDATE_LISTING = "UPDATE_LISTING";
export const DELETE_LISTING = "DELETE_LISTING";
export const FETCH_LISTINGS = "FETCH_LISTINGS";
export const SET_LISTINGS_LOADING = "SET_LISTINGS_LOADING";
