export const SET_LISTINGS = "SET_LISTINGS";
export const CREATE_LISTING = "CREATE_LISTING";
export const UPDATE_LISTING = "UPDATE_LISTING";
export const DELETE_LISTING = "DELETE_LISTING";
export const SET_LISTINGS_LOADING = "SET_LISTINGS_LOADING";
export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";
